<a href="https://colab.research.google.com/github/alik604/Cuda/blob/master/CuPy_Regularize_least_squares%2C_given_only_pinv().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
# !pip install cupy-cuda102

import math
import pandas as pd
import numpy as np
import cupy as cp
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [2]:
N = 50
x = cp.concatenate([cp.arange(N),cp.arange(N)]).reshape(2,-1)
y = cp.arange(N)
A = x
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [3]:
U, D, V = cp.linalg.svd(A) # https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.9-The-Moore-Penrose-Pseudoinverse/
A.shape # (2,100)
V.shape # (100,100)
D.shape # (2,1)
U.shape # (2,2) ^ t 
        # A^+ = V  D^+  U^T

(2, 50)

(50, 50)

(2,)

(2, 2)

In [4]:
D_plus = cp.zeros((A.shape[0], A.shape[1])).T # (100,2)
D_plus[:D.shape[0], :D.shape[0]] = cp.linalg.inv(cp.diag(D))

print('\n\nD plus\n',D_plus)

print('D:\n',D)
print('\ndiag(D):\n',cp.diag(D))
print('\ninv(diag(D)))\n',cp.linalg.inv(cp.diag(D)))

A_plus = V.T.dot(D_plus).dot(U.T) # equal in theory :'( or i cant follow a blog which shows it working. yes i tried the included the example... https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.9-The-Moore-Penrose-Pseudoinverse/
A_plus = cp.linalg.pinv(A)
print('\n\n A plus\n',A_plus)
# cp.linalg.pinv(A) # [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
# np.linalg.pinv(A.tolist()) # array([[0, 1, 2, 3, 4],[0, 1, 2, 3, 4]])
## non equal 



D plus
 [[3.51689974e-03 0.00000000e+00]
 [0.00000000e+00 1.92418334e+13]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]


In [5]:
inv = x.transpose().dot(x)
inv = cp.linalg.pinv(inv)
B = inv.dot(x.transpose())
B

array([[0.00000000e+00, 0.00000000e+00],
       [1.23685838e-05, 1.23685838e-05],
       [2.47371676e-05, 2.47371676e-05],
       [3.71057514e-05, 3.71057514e-05],
       [4.94743352e-05, 4.94743352e-05],
       [6.18429190e-05, 6.18429190e-05],
       [7.42115028e-05, 7.42115028e-05],
       [8.65800866e-05, 8.65800866e-05],
       [9.89486704e-05, 9.89486704e-05],
       [1.11317254e-04, 1.11317254e-04],
       [1.23685838e-04, 1.23685838e-04],
       [1.36054422e-04, 1.36054422e-04],
       [1.48423006e-04, 1.48423006e-04],
       [1.60791589e-04, 1.60791589e-04],
       [1.73160173e-04, 1.73160173e-04],
       [1.85528757e-04, 1.85528757e-04],
       [1.97897341e-04, 1.97897341e-04],
       [2.10265925e-04, 2.10265925e-04],
       [2.22634508e-04, 2.22634508e-04],
       [2.35003092e-04, 2.35003092e-04],
       [2.47371676e-04, 2.47371676e-04],
       [2.59740260e-04, 2.59740260e-04],
       [2.72108844e-04, 2.72108844e-04],
       [2.84477427e-04, 2.84477427e-04],
       [2.968460

In [185]:
B.transpose().dot(y)

array([0.5, 0.5])

In [0]:
# N = 6
# x = cp.arange(N)[1:]
# x = np.concatenate([x,x]).reshape(2,-1)
# y = np.arange(N)[1:]
# print('matrix:\n',x)

# #https://en.wikipedia.org/wiki/Linear_least_squares#Main_formulations
# inv = x.transpose().dot(x)
# inv = np.linalg.pinv(inv)
# B = inv.dot(x.transpose())
# print('weigths: ',B.transpose().dot(y))

In [9]:
np.linalg.lstsq(np.array(x.tolist()).transpose(),np.array(y.tolist()))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([0.5, 0.5]),
 array([], dtype=float64),
 1,
 array([2.84341344e+02, 3.12428059e-14]))

## Regularize 
pg 8: http://web.stanford.edu/class/archive/ee/ee263/ee263.1042/min-norm

In [11]:
# np.diag(np.ones(N)) # IdentityMatrix I_N

# choose MU
MU = 0.3

# this is probably a terrible choice, my sources neglects guidance on MU; see last page


N = 10
x = np.arange(N)
x = np.concatenate([x,x]).reshape(2,-1)
y = np.arange(N)
print('matrix:\n',x)

#https://en.wikipedia.org/wiki/Linear_least_squares#Main_formulations
xx = x.transpose().dot(x)
reg = MU * np.diag(np.ones(N))
inv = np.linalg.pinv(xx + reg) # x = (AT*A + µI)^−1 A^T * y
B = inv.dot(x.transpose())
print('weigths: ',B.transpose().dot(y))

matrix:
 [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
weigths:  [0.49973698 0.49973698]
